[#985] Aws integration
legion-platform/legion pull request #1024
Opened 2019-10-11 08:38 UTC by mcdoker18

* Fixed aws support in connections
* Added new type of connection: ecr
* Integrate rest packer with ecr
* Update certificates in all golang images
* Operator can create a pull k8s secret from docker connections

2019-10-11 18:46 UTC, maxkochubey requested changes

2019-10-11 18:46 UTC, maxkochubey commented on legion/operator/pkg/webserver/routes/v1/connection/connection_validation_test.go
> +func TestECRTypeValidationUrl(t *testing.T) {
Next two functions are named `TestEcr...` and this one - `TestECR...`.

2019-10-14 07:16 UTC, mcdoker18 commented on legion/operator/pkg/webserver/routes/v1/connection/connection_validation_test.go
> +func TestECRTypeValidationUrl(t *testing.T) {
Fixed

2019-10-14 08:59 UTC, maxkochubey submitted a review, later dismissed

2019-10-24 09:51 UTC, vlad-tokarev commented on legion/operator/pkg/controller/modeldeployment/pull_connections.go
> +	dockerURI, err := url.Parse("https://" + conn.Spec.URI)
Maybe we should check whether the schema is provided and attach this only if User skip this?

2019-10-24 09:56 UTC, mcdoker18 commented on legion/operator/pkg/controller/modeldeployment/pull_connections.go
> +	dockerURI, err := url.Parse("https://" + conn.Spec.URI)
Users must not provide a schema. I can add a connection validation in EDI, is it ok?

2019-10-24 09:58 UTC, vlad-tokarev submitted a review, later dismissed

2019-10-24 10:00 UTC, vlad-tokarev commented on legion/operator/pkg/controller/modeldeployment/pull_connections.go
> +	dockerURI, err := url.Parse("https://" + conn.Spec.URI)
I think it will be nice because the user can get feedback about this error immediately rather than get an exception later. But as you wish

2019-10-24 10:16 UTC, maxkochubey commented on legion/tests/e2e/robot/tests/e2e/resources/tensorflow/training.legion.yaml
> +      cpu: 1024Mi
`Mi` for CPU resource?

2019-10-24 10:29 UTC, mcdoker18 commented on legion/tests/e2e/robot/tests/e2e/resources/tensorflow/training.legion.yaml
> +      cpu: 1024Mi
I wonder, why does it work?...
Fixed

2019-10-24 10:33 UTC, mcdoker18 commented on legion/operator/pkg/controller/modeldeployment/pull_connections.go
> +	dockerURI, err := url.Parse("https://" + conn.Spec.URI)
If you do not mind, then I'll fix it in my next PR.
Because I should find a proper way to make it.

2019-10-24 10:33 UTC, maxkochubey approved these changes

2019-10-24 11:36 UTC, karbyshevds approved these changes

2019-10-24 11:38 UTC, merged