[#499][#732][#777] Improvement Grafana deployment
legion-platform/legion pull request #785
Opened 2019-02-07 12:34 UTC by mcdoker18

* Replaced docker image by official one
* Replaced helm deployment by official helm chart
* Added PV and PVC
* Configurable grafana user/password
* Minor fixed

2019-02-07 14:40 UTC, kirillmakhonin commented
Maybe we may generate secrets such as Grafana password on deploy? And persist it in Secret for future usage.

2019-02-07 14:47 UTC, kirillmakhonin commented
ok to test

2019-02-07 14:50 UTC, mcdoker18 commented
> Maybe we may generate secrets such as Grafana password on deploy? And persist it in Secret for future usage.

I don't like it. A couple of problems:
* How should we pass the password to the robot test in your case?
* You also must have access to the k8s to use Grafana.
* Out current upgrade strategy is to delete everything in a namespace and create new deployments. The new password will generate again and again.

2019-02-18 11:51 UTC, mcdoker18 commented
bot, test all

2019-02-18 13:39 UTC, kirillmakhonin submitted a review, later dismissed

2019-02-18 14:39 UTC, botsman requested changes

2019-02-18 14:39 UTC, skayerok commented on deploy/helms/legion-core/templates/metrics/gradana_configmaps.yaml
> +---
typo in filename: `gradana_configmaps.yaml`

2019-02-18 14:39 UTC, skayerok commented on deploy/helms/legion/templates/metrics/gradana_configmaps.yaml
> +---
same

2019-02-18 21:28 UTC, mcdoker18 commented
bot, test all

2019-02-24 17:37 UTC, mcdoker18 commented
bot, test all

2019-02-25 07:48 UTC, alexander-semenets commented on Jenkinsfile
> +
extra blank line

2019-02-25 08:05 UTC, mcdoker18 commented on Jenkinsfile
> +
Fixed

2019-02-25 09:36 UTC, kirillmakhonin approved these changes

2019-02-25 09:39 UTC, botsman approved these changes

2019-02-25 10:20 UTC, alexander-semenets approved these changes

2019-02-25 10:26 UTC, merged