[#714] calico cni
legion-platform/legion pull request #792
Opened 2019-02-12 10:04 UTC by alexander-semenets

KOPS and K8S version were updated for better compatibility with latest calico version

2019-02-12 10:05 UTC, alexander-semenets commented
bot, test all

2019-02-12 12:38 UTC, alexander-semenets commented
bot, test all

2019-02-12 16:29 UTC, kirillmakhonin commented
bot, test all

2019-02-12 18:33 UTC, mcdoker18 requested changes

2019-02-12 18:33 UTC, mcdoker18 commented on deploy/ansible/roles/k8s_create_cluster/tasks/install-kops.yaml
> +#    sha256sum: "{{ kops_sha256sum }}"
Please, revert the checksum

2019-02-12 18:33 UTC, mcdoker18 commented on deploy/ansible/roles/k8s_create_cluster/defaults/main.yaml
> +# kope.io/k8s-1.10-debian-jessie-amd64-hvm-ebs-2018-08-17
Remove commented lines

2019-02-12 18:33 UTC, mcdoker18 commented on deploy/ansible/roles/k8s_create_cluster/templates/kops.yaml.j2
> +#  kubeAPIServer:
Remove the commented lines

2019-02-12 18:33 UTC, mcdoker18 commented on k8s/ansible/Dockerfile
> +ENV KOPS_VERSION=1.11.0
Upgrade kubectl version too

2019-02-12 20:57 UTC, alexander-semenets commented
all comments have been addressed

2019-02-12 20:57 UTC, alexander-semenets commented
bot, test all

2019-02-12 20:58 UTC, mcdoker18 approved these changes

2019-02-13 07:02 UTC, kirillmakhonin approved these changes

2019-02-13 08:49 UTC, botsman approved these changes

2019-02-13 13:38 UTC, alexander-semenets commented
bot, test all

2019-02-13 17:51 UTC, alexander-semenets commented
bot, test all

2019-02-14 05:50 UTC, alexander-semenets commented
bot, test all

2019-02-14 06:06 UTC, alexander-semenets commented
bot, test all

2019-02-14 07:15 UTC, merged