[#808] non root pipeline jobs
legion-platform/legion pull request #817
Opened 2019-02-22 07:36 UTC by alexander-semenets

this fixes #808

2019-02-25 06:39 UTC, alexander-semenets commented
bot, test all

2019-02-25 11:43 UTC, alexander-semenets commented
bot, test all

2019-02-25 15:15 UTC, mcdoker18 requested changes

2019-02-25 15:15 UTC, mcdoker18 commented on Jenkinsfile
> +                            docker.image("legion/legion-docker-agent:${Globals.buildVersion}").inside("-v /var/run/docker.sock:/var/run/docker.sock -u root") {
Why did you add root user?
I think it a reason for the failed job https://cc.epm.kharlamov.biz/jenkins/job/Build_Legion_Artifacts/1655/

2019-02-25 15:15 UTC, mcdoker18 commented on deploy/helms/airflow/templates/mq.yaml
> +        image: "redis:3"
Can you specify precise version?

2019-02-25 15:15 UTC, mcdoker18 commented on deploy/helms/airflow/templates/db.yaml
> +        image: "postgres:10"
Can you specify precise version?

2019-02-26 08:22 UTC, alexander-semenets commented
bot, test all

2019-02-26 08:54 UTC, mcdoker18 submitted a review, later dismissed

2019-02-26 12:03 UTC, alexander-semenets commented
bot, test all

2019-02-26 16:17 UTC, mcdoker18 commented
bot, test all

2019-02-27 08:44 UTC, alexander-semenets commented
bot, test all

2019-02-27 10:47 UTC, mcdoker18 approved these changes

2019-02-27 10:58 UTC, merged