[#811] Revoke host docker socket from model pods
legion-platform/legion pull request #820
Opened 2019-02-24 21:14 UTC by mcdoker18

* Added new parameter for the legionctl command: `--build-type`.
  Currently, it supports the following values:
    * `docker-socket` - builds a model image using a docker socket. It
      is the default value.
    * `docker-remote` - does not build image yourself. Send an HTTP
      request to the `MODEL_DOCKER_BUILDER_URL` server that determines
      the model container, build and pushes it.
    * `kaniko` or `buildah` will be supported in the near future.
* Added the second container to slave model Jenkins pod that will build
a model docker image.

2019-02-25 11:01 UTC, kirillmakhonin requested changes

2019-02-25 11:01 UTC, kirillmakhonin commented on k8s/jenkins/legion-jenkins-plugin/src/main/resources/legion.groovy
>                      hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock'),
Why?

2019-02-25 11:01 UTC, kirillmakhonin commented on k8s/jenkins/legion-jenkins-plugin/src/main/resources/legion.groovy
> +                                    persistentVolumeClaim(claimName: env.DAGS_VOLUME_PVC, mountPath: env.AIRFLOW_DAGS_DIRECTORY)
Please remove

2019-02-25 11:01 UTC, kirillmakhonin commented on legion/legion/cli.py
> +    if args.build_type == 'docker-socket':
Please use constants or Enums

2019-02-25 11:01 UTC, kirillmakhonin commented on legion/legion/cli.py
> +    build_model_parser.add_argument('--build-type', default='docker-socket',
Please use choices

2019-02-25 11:01 UTC, kirillmakhonin commented on legion/legion/config.py
> +                                                     'Model docker builder url', False)
Please extend description of new config variables

2019-02-25 11:01 UTC, kirillmakhonin commented on legion/legion/containers/server.py
> +    model_container_id = get_container_id_of_current_pod('model')
Please use constants

2019-02-25 11:01 UTC, kirillmakhonin commented on legion/legion/containers/server.py
> +AUTH_COOKIE_NAME = '_oauth2_proxy'
Please remove

2019-02-25 11:01 UTC, kirillmakhonin commented on legion/legion/containers/server.py
> +TEMPLATES_FOLDER = os.path.abspath(os.path.join(
Redundant

2019-02-25 11:01 UTC, kirillmakhonin commented on legion/legion/containers/wsgi.py
> +from legion.containers.server import init_application
Can we remove this file?

2019-02-25 11:01 UTC, kirillmakhonin commented on legion/legion/external/docker.py
> +    resp = requests.post(config.MODEL_DOCKER_BUILDER_URL.strip('/') + DOCKER_BUILD_URL,  # pylint: disable=E1101
Please add exception handling

2019-02-25 11:01 UTC, kirillmakhonin commented on legion/legion/external/docker.py
> +    return resp.json()["image_name"]
Please use NamedTuple

2019-02-26 21:14 UTC, mcdoker18 commented
bot, test all

2019-02-27 16:26 UTC, mcdoker18 commented
bot, test all

2019-02-28 10:15 UTC, mcdoker18 commented
bot, test all

2019-02-28 11:31 UTC, mcdoker18 commented
bot, test all

2019-03-01 08:43 UTC, kirillmakhonin approved these changes

2019-03-01 09:25 UTC, botsman approved these changes

2019-03-01 13:14 UTC, alexander-semenets approved these changes

2019-03-01 13:15 UTC, merged