[#823] Model build operator
legion-platform/legion pull request #858
Opened 2019-04-10 09:38 UTC by mcdoker18

* Remove jenkins from helm charts
* Remove the core helm chart because it is empty
* Added operator which only build a model
* Added docker containers for the build and operator containers
* Now model is built during e2e tests instead of Jenkins build phase
* Replaced Jenkisfiles in examples with model training crd

This closes #823

2019-04-11 08:10 UTC, alexander-semenets commented on containers/operator/Dockerfile
> +#########################################################
Copyright is missed.

2019-04-11 08:10 UTC, alexander-semenets commented on containers/operator/Dockerfile
> +#########################################################
Can we put all Dockerfiles to a common view please.

2019-04-11 08:10 UTC, alexander-semenets commented on containers/operator/Dockerfile
> +# TODO: fixed
abandoned todo

2019-04-11 08:10 UTC, alexander-semenets commented on containers/pipeline-agent/Dockerfile
> +# Used for robot tests
copyright is missed

2019-04-11 08:10 UTC, alexander-semenets commented on containers/operator/Dockerfile
> +#########################################################
Some comments about each image purpose would be useful

2019-04-11 08:10 UTC, alexander-semenets commented on containers/operator/Dockerfile
> +RUN ssh-keyscan github.com > /etc/ssh/ssh_known_hosts
Do we really want to freeze the key in image? Shouldn't it be better set up at the place where we do checkout dynamically? I guess the keys may be update.

2019-04-11 08:10 UTC, alexander-semenets commented on legion/operator/Makefile
> +IMG ?= legion/operator:latest
for prod and stage releases we use legionplatform and legionplatformtest registries respectively.
Wouldn't it be a problem if we have legion/ registry strictly defined here?

2019-04-11 08:10 UTC, alexander-semenets commented on legion/operator/Makefile
> +TARGET_YAML_STORAGE = ${TARGET_HELM_CHART}/templates/operator/generated
I guess those paths /build and /deploy are not valid any more?

2019-04-12 08:04 UTC, kirillmakhonin requested changes

2019-04-12 08:04 UTC, kirillmakhonin commented on legion/operator/pkg/builder/builder.go
> +			return container.ContainerID[len("docker://"):], nil
Please use constants

2019-04-12 08:04 UTC, kirillmakhonin commented on legion/operator/pkg/utils/git.go
> +		Auth:     gitAuth,
Does it work with https://... Git URLs?

2019-04-12 08:04 UTC, kirillmakhonin commented on legion/operator/pkg/utils/git.go
> +	privateSshKeyFile := "/home/root/.ssh/id_rsa"
Looks like this should be ENV configurable.

2019-04-12 09:13 UTC, mcdoker18 commented on legion/operator/Makefile
> +IMG ?= legion/operator:latest
Removed the variable and target

2019-04-12 09:14 UTC, mcdoker18 commented on containers/operator/Dockerfile
> +#########################################################
Please, explain what do you mean.

2019-04-16 12:14 UTC, kirillmakhonin submitted a review, later dismissed

2019-04-17 07:31 UTC, mcdoker18 commented
bot, test app

2019-04-17 10:06 UTC, mcdoker18 commented
bot, test all

2019-04-17 10:07 UTC, mcdoker18 commented
bot, test app

2019-04-17 10:30 UTC, mcdoker18 commented
bot, test app

2019-04-17 12:18 UTC, mcdoker18 commented
bot, test app

2019-04-17 13:50 UTC, mcdoker18 commented
bot, test app

2019-04-17 14:40 UTC, mcdoker18 commented
bot, test app

2019-04-17 14:51 UTC, mcdoker18 commented
bot, test app

2019-04-17 15:49 UTC, kirillmakhonin approved these changes

2019-04-17 18:08 UTC, alexander-semenets approved these changes

2019-04-17 18:09 UTC, merged