[#859] Replace edge with istio
legion-platform/legion pull request #939
Opened 2019-07-19 09:29 UTC by mcdoker18

* Removed the edge container and helm
* Removed the legion-service package and his unit tests
* Removed the python e2e tests
* Changed internal model api. `api/model/{id}/{version}` -> `/api/model`
* Added new deployment traffic collector. It sniffs traffic from istio ingress gateway.
* Refactored webhook and validation
* Added new dashboard for deployment
* Renamed model id -> model name
* Added new API for routing

This closes #859
This closes #101
This closes #904
This closes #14
This closes #207

2019-07-23 08:08 UTC, kirillmakhonin requested changes

2019-07-23 08:08 UTC, kirillmakhonin commented on containers/operator/Dockerfile
> +RUN GOOS=linux GOARCH=amd64 make build-all && (make test || true)
Why did you ignore errors?

2019-07-23 08:08 UTC, kirillmakhonin commented on examples/Sklearn-Income/modeldeployment.legion.yaml
> +  max_replicas: 2
Please use `camelCase`

2019-07-23 08:08 UTC, kirillmakhonin commented on legion/cli/legion/cli/parsers/deployment.py
> +            max_replicas=args.max_replicas,
Please use `camelCase`

2019-07-23 08:08 UTC, kirillmakhonin commented on legion/cli/legion/cli/parsers/deployment.py
> +        f'{md.min_replicas}/{md.available_replicas}/{md.max_replicas}',
Please use `camelCase`

2019-07-23 08:08 UTC, kirillmakhonin commented on helms/legion/templates/edge-gateway.yaml
> +  name: "edge"
@mcdoker18 , could you, please, inject ReleaseName inside resource names as in other chart resources?

2019-07-23 08:08 UTC, kirillmakhonin commented on helms/legion/templates/operator/operator-vsc.yaml
> -  labels:
Why did you remove labels?

2019-07-23 08:08 UTC, kirillmakhonin commented on legion/operator/cmd/operator/main.go
> +	log.Info("Registerifng Components.")
Typo

2019-07-23 08:08 UTC, kirillmakhonin commented on legion/operator/pkg/apis/legion/v1alpha1/modeldeployment_types.go
> +	// Current number of pods
Please make description more informative (what are differences between `AvailableReplicas` and `Replicas`.

2019-07-23 08:08 UTC, kirillmakhonin commented on legion/operator/pkg/apis/legion/v1alpha1/modeldeployment_validation.go
> +	if md.Spec.MaxReplicas != nil && md.Spec.MinReplicas != nil && *md.Spec.MinReplicas > *md.Spec.MaxReplicas {
Does we check that `MaxReplicas` and `MinReplicas` >= 0?

2019-07-23 08:08 UTC, kirillmakhonin commented on legion/operator/pkg/controller/modelroute/modelroute_controller.go
> +							Attempts:      30,
Should this be configurable?

2019-07-23 08:08 UTC, kirillmakhonin commented on legion/operator/pkg/controller/modelroute/modelroute_controller.go
> +							Attempts:      30,
This too

2019-07-23 08:08 UTC, kirillmakhonin commented on legion/operator/pkg/webhook/default_server/server.go
> +					"app.kubernetes.io/component": "webhook-server",
Maybe `legion-webhook-server`

2019-07-23 08:08 UTC, kirillmakhonin commented on legion/sdk/legion/sdk/templates/docker_files/uwsgi.ini
> +processes = 4
Why did you keep this file?

2019-07-23 08:11 UTC, kirillmakhonin commented on containers/operator/Dockerfile
> +RUN GOOS=linux GOARCH=amd64 make build-all && (make test || true)
OK

2019-07-23 09:04 UTC, mcdoker18 commented on helms/legion/templates/edge-gateway.yaml
> +  name: "edge"
Fixed

2019-07-23 09:09 UTC, mcdoker18 commented on helms/legion/templates/operator/operator-vsc.yaml
> -  labels:
Fixed

2019-07-23 09:09 UTC, mcdoker18 commented on legion/operator/cmd/operator/main.go
> +	log.Info("Registerifng Components.")
Fixed

2019-07-23 09:13 UTC, mcdoker18 commented on legion/operator/pkg/apis/legion/v1alpha1/modeldeployment_types.go
> +	// Current number of pods
Fixed

2019-07-23 09:16 UTC, mcdoker18 commented on legion/operator/pkg/apis/legion/v1alpha1/modeldeployment_validation.go
> +	if md.Spec.MaxReplicas != nil && md.Spec.MinReplicas != nil && *md.Spec.MinReplicas > *md.Spec.MaxReplicas {
Yep. This code is a couple of lines above.
```go
		if *md.Spec.MaxReplicas < 1 {
			err = multierr.Append(errors.New(mdMaxReplicasErrorMessage), err)
		}
...		
                if *md.Spec.MinReplicas < 0 {
			err = multierr.Append(errors.New(mdMinReplicasErrorMessage), err)
		}
```

2019-07-23 09:20 UTC, mcdoker18 commented on legion/operator/pkg/controller/modelroute/modelroute_controller.go
> +							Attempts:      30,
IMHO, At the moment, there is no need to make the interface more complicated.

2019-07-23 09:24 UTC, mcdoker18 commented on legion/operator/pkg/webhook/default_server/server.go
> +					"app.kubernetes.io/component": "webhook-server",
Noop. All our components doesn't have the "legion" prefix

2019-07-23 09:25 UTC, mcdoker18 commented on legion/operator/pkg/webhook/default_server/server.go
> +					"app.kubernetes.io/component": "webhook-server",
Fixed

2019-07-23 09:27 UTC, mcdoker18 commented on legion/sdk/legion/sdk/templates/docker_files/uwsgi.ini
> +processes = 4
Removed dir

2019-07-23 10:08 UTC, kirillmakhonin reviewed
Please await for jupyterlab plugin changes

2019-07-23 11:29 UTC, kirillmakhonin commented
JupyterLab plugin has been fixed.

2019-07-23 11:32 UTC, kirillmakhonin requested changes
Please fix next things:
1. Add returning of `Request-ID` header for each model invocation (with generated or with manual set `Request-ID` header in request)
2. Rename all Legion-related headers to one naming convention (`X-Model-Name` to `Model-Name` and etc)
3. Add support of parsing HTTP POST variables in request & response capturing.
4. Fix or remove HTTP POST variables gathering in feedback aggregator.

2019-07-23 19:18 UTC, karbyshevds submitted a review, later dismissed

2019-07-24 17:07 UTC, karbyshevds approved these changes

2019-07-25 08:57 UTC, kirillmakhonin approved these changes

2019-07-25 09:03 UTC, alexander-semenets approved these changes

2019-07-25 09:04 UTC, merged