[#955] Jupyter inside helm
legion-platform/legion pull request #960
Opened 2019-07-30 13:23 UTC by kirillmakhonin

This closes #955

2019-07-30 13:28 UTC, kirillmakhonin commented
bot, test all

2019-07-30 14:09 UTC, mcdoker18 requested changes

2019-07-30 14:09 UTC, mcdoker18 commented on helms/legion/values.yaml
> +  resources:
IMHO, we should increase the default resources.

2019-07-30 14:09 UTC, mcdoker18 commented on helms/legion/values.yaml
> +      memory: "512Mi"
Please, add a robot test. It should check that the jupiterlab deployment is up and closed by dex.

2019-07-30 14:19 UTC, karbyshevds submitted a review, later dismissed

2019-08-02 12:58 UTC, mcdoker18 commented on helms/legion/values.yaml
> +  resources:
Fixed

2019-08-02 12:58 UTC, mcdoker18 commented on helms/legion/values.yaml
> +      memory: "512Mi"
Fixed

2019-08-02 12:58 UTC, mcdoker18 commented
bot, test app

2019-08-02 14:51 UTC, mcdoker18 commented
bot, test gcp app

2019-08-06 08:21 UTC, alexander-semenets approved these changes

2019-08-06 13:20 UTC, karbyshevds approved these changes

2019-08-06 13:47 UTC, maxkochubey approved these changes

2019-08-06 15:55 UTC, mcdoker18 approved these changes

2019-08-06 15:56 UTC, merged